//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuitoText_1._0.Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class COMPRACARRITO
    {
        public int Compra_ID { get; set; }

        [Display(Name = "Usuario")]
        public string User_Id { get; set; }
        [Display(Name = "Nombre del Producto")]
        public Nullable<int> Prod_id { get; set; }
        [Display(Name = "Fecha de Compra")]
        public Nullable<System.DateTime> FechaCompra { get; set; }
        [Display(Name = "Estado")]
        public Nullable<int> State_Compra { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
    }
}
