//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuitoText_1._0.Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public int US_ID { get; set; }
        [Display(Name = "Nombre")]
        public string US_NOMBRE { get; set; }
        [Display(Name = "Dirección")]
        public string US_DIRECCION { get; set; }
        [Display(Name = "Cedula")]
        public string US_CEDULA { get; set; }
        [Display(Name = "Teléfono")]
        public string US_TELEFONO { get; set; }
        public string US_TIPO { get; set; }
        [Display(Name = "Email")]
        public string US_EMAIL { get; set; }
        [Display(Name = "Contraseña")]
        public string US_PASSWORD { get; set; }
        [Display(Name = "Confirme Contraseña ")]
        public string US_CONFIRMPASWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
